# Generated by Django 4.0.5 on 2022-07-04 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totogg', '0004_rename_teascore_scd_rank_score_scd'),
    ]

    operations = [
        migrations.CreateModel(
            name='summerSummary',
            fields=[
                ('tname', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('rate', models.FloatField()),
                ('kill', models.FloatField()),
                ('gold', models.IntegerField()),
                ('baron', models.FloatField()),
                ('dragon', models.FloatField()),
                ('tower', models.FloatField()),
            ],
        ),
    ]
