# Generated by Django 4.0.5 on 2022-07-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totogg', '0007_rank_score_n'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='team_logo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
