# Generated by Django 4.0.5 on 2022-07-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totogg', '0012_recentsummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='gameSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('team1', models.CharField(max_length=20)),
                ('team2', models.CharField(max_length=20)),
            ],
        ),
    ]
