# Generated by Django 4.0.5 on 2022-07-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totogg', '0013_gameschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameschedule',
            name='time',
            field=models.CharField(max_length=50),
        ),
    ]
